entries/blueprint.py
from flask import Blueprint, g

from helpers import object_list, entry_list, get_entry_or_404, filter_status_by_user
from models import Entry, Tag

from flask import render_template, redirect, url_for, request, flash

from entries.forms import EntryForm, ImageForm, CommentForm

from app import db, app

import os
from werkzeug import security

from flask_login import login_required

entries = Blueprint('entries', __name__, template_folder='templates')

@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)

@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)

@entries.route('/tags/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)

@entries.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug, author=None)
    form = CommentForm(data={'entry_id': entry.id})
    return render_template('entries/detail.html', entry=entry, form=form)

@entries.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():  # if request.form get entry modified Entry
            entry = form.save_entry(Entry(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm()
    return render_template('entries/create.html', form=form)

@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" has been saved.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)

@entries.route('/<slug>/delete', methods=['GET', 'POST'])
def delete(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Entry "%s" has been deleted.' % entry.title, 'success')
        return redirect(url_for('entries.index'))
    
    return render_template('entries/delete.html', entry=entry)

@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename =   security.safe_join(app.config['IMAGES_DIR'], image_file.filename)
            image_file.save(filename)
            flash('Saved %s' % os.path.basename(filename), 'success')
            return redirect(url_for('entries.index'))
    else:
        form = ImageForm()

    return render_template('entries/image_upload.html', form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | My Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style type="text/css">
        body { padding-top: 60px; }
    </style>
    {% block extra_style %}{% endblock %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block extra_script %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">       
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    {% block branding %}My Blog{% endblock %}
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('homepage') }}">Home</a></li>
                    <li><a href="{{ url_for('entries.index') }}">Blog</a></li>
                    <li><a href="{{ url_for('entries.tag_index') }}">Tags</a></li>
                    <li><a href="{{ url_for('entries.create') }}">Create</a></li>
                    {% if g.user.is_authenticated %}
                    <li><a href="{{ url_for('logout', next=request.path) }}">Logout</a></li>
                    {% else %}
                    <li><a href="{{ url_for('login', next=request.path )}}">Login</a></li>
                    {% endif %}
                    {% block extra_nav %}{% endblock %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{% block content_title %}{% endblock %}</h1><hr />
                {% for category, message in get_flashed_messages(with_categories=True) %}
                <div class="alter alter-dismissable alter-{{ category }}">
                    <button type="button" class="close" data-dismiss='alter'>&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-3">
                {% block sidebar %}
                <ul class="well nav nav-stacked">
                    <li><a href="%">sidebar item</a></li>
                </ul>
                {% endblock %}
            </div>
        </div>
        <div class="row">
            <hr />
            <footer>
                <p>&copy; your name</p>
            </footer>
        </div>
    </div>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}

{% block content_title %}Welcome to my blog{% endblock %}

{% block content %}
    {% if number %}
    <p>Your number is {{ number|int }}
        <ul>
        {% for i in range(number|int) %}
            {% if i is divisibleby 2 %}
                <li>{{ i }}</li>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
    <p>Your name is {{ name|default('<unknown>', True) }}.</p>
    {% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Log in{% endblock %}
{% block content_title %}Log in{% endblock %}
{% block content %}
<form action="{{ url_for('login', next=request.args.get('next', '')) }}" class="form form-horizontal" method="post">
{{ form_field(form.email) }}
{{ form_field(form.password) }}
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <div class="checkbox">
            <label>{{ form.remember_me() }} Remenber me</label>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9"> 
        <button type="submit" class="btn btn-default">Log in</button>
        <a class="btn" href={{ url_for("homepage") }}>Cancel</a>
    </div>
</div>
</form>
{% endblock %}